### PR TITLE
Adding print() from TrackerTopology

### PR DESCRIPTION
**Pull request by vidalm**

### CODE REVIEW

**Review by pieterdavid — APPROVED** [review]
Looks good to me. We have a few more small changes to do in Fireworks/Core and Fireworks/Tracks, maybe we can group those into one cmssw PR?

**Comment by vidalm** [comment]
Ok, fine with me. How we do then. We merge the PRs here and we cherry-pick all of them for the cmssw PR?

**Comment by OlivierBondu** [comment]
maybe a stupid question but: why do we care about merging the PRs here ? we just care about the (internal) review now since last Wed, no ? we don't want a gigantic PR on this branch anymore, this is just for convenience of review that we continue pushing here ?

**Comment by pieterdavid** [comment]
you're right, it's only for the convenience of review, so we could as well not merge them (except that then we can't abuse github as a todo list any more ;-) )

**Review by OlivierBondu — APPROVED** [review]

**Comment by vidalm** [comment]
Merging

**Pull request merged**
