### PR TITLE
Deprecating T(IB|OB|ID|EC)DetId types in RecoMuon/TrackerSeedGenerator

### PR DESCRIPTION
**Pull request by OlivierBondu**
it compiles :)

### CODE REVIEW

**Review by pieterdavid — APPROVED** [review]
Looks good, thanks! I'm wondering whether passing `const edm::ESHandle<TrackerTopology>&` to `findSeedsOnLayer` and `makeSeedsFromHits` is optimal... I think I would have made that just `const TrackerTopology*` because it's simpler, but no strong preference. We can also see if anyone complains later on

**Comment by OlivierBondu** [comment]
I have no idea which is better :smile:

**Comment by OlivierBondu** [comment]
submitted: https://github.com/cms-sw/cmssw/pull/19148

**Comment by alesaggio** [comment]
Looks good to me! :)

**Review by vidalm — APPROVED** [review]
Fine

**Review by alesaggio — APPROVED** [review]

**Pull request merged**
